#energy all countries against time line graph
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv('UN data.csv', delimiter=',', encoding="utf-8-sig")



def graph():
    canada = df.loc[df['Country or Area'] == "Canada"]
    canada_years = canada['Year']
    canada_quant = canada['Quantity']
    plt.plot(canada_years, canada_quant, label="Canada")
    china = df.loc[df['Country or Area'] == "China"]
    china_years = china['Year']
    china_quant = china['Quantity']
    plt.plot(china_years, china_quant, label="China")
    france = df.loc[df['Country or Area'] == "France"]
    france_years = france['Year']
    france_quant = france['Quantity']
    plt.plot(france_years, france_quant, label="France")
    korea = df.loc[df['Country or Area'] == "Korea, Republic of"]
    korea_years = korea['Year']
    korea_quant = korea['Quantity']
    plt.plot(korea_years, korea_quant, label="Korea")
    uk = df.loc[df['Country or Area'] == "United Kingdom"]
    uk_years = uk['Year']
    uk_quant = uk['Quantity']
    plt.plot(uk_years, uk_quant, label="UK")
    plt.legend()
    plt.show()

def percentage_change():
    canada = df.loc[df['Country or Area'] == "Canada"]
    canada_quant = canada['Quantity']
    canada_percentage_change = ((canada_quant.iloc[-1] - canada_quant.iloc[0]) / canada_quant.iloc[-1])*100
    china = df.loc[df['Country or Area'] == "China"]
    china_quant = china['Quantity']
    china_percentage_change = ((china_quant.iloc[-1] - china_quant.iloc[0]) / china_quant.iloc[-1]) * 100
    france = df.loc[df['Country or Area'] == "France"]
    france_quant = france['Quantity']
    france_percentage_change = ((france_quant.iloc[-1] - france_quant.iloc[0]) / france_quant.iloc[-1]) * 100
    korea = df.loc[df['Country or Area'] == "Korea, Republic of"]
    korea_quant = korea['Quantity']
    korea_percentage_change = ((korea_quant.iloc[0] - korea_quant.iloc[-1]) / korea_quant.iloc[0]) * 100
    uk = df.loc[df['Country or Area'] == "United Kingdom"]
    uk_quant = uk['Quantity']
    uk_percentage_change = ((uk_quant.iloc[-1] - uk_quant.iloc[0]) / uk_quant.iloc[-1]) * 100
    print("Percentage changes by country in mKw/h of energy generated by tidal waves, relative to year when measurements started: \n Canada: {} \n China: {} \n France: {} \n Republic of Korea: {} \n UK: {}".format(canada_percentage_change, china_percentage_change, france_percentage_change, korea_percentage_change, uk_percentage_change))
    return canada_percentage_change, china_percentage_change, france_percentage_change, korea_percentage_change, uk_percentage_change

percentage_change()
graph()